services:
  news-aggregator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # Mount env file if it exists
      - ./.env.local:/app/.env.local:ro
    restart: unless-stopped
    container_name: innoscripta-news-aggregator
    
  # Optional: Add a development service
  news-aggregator-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    container_name: innoscripta-news-aggregator-dev
    profiles:
      - dev