// can no longer use this pattern, News API randomized image urls, this cannot be dynamically determined within the time constraint

export const imageHostnames = [
  "i.insider.com",
  "npr.brightspotcdn.com",
  "www.washingtonpost.com",
  "ichef.bbci.co.uk",
  "nbcsports.brightspotcdn.com",
  "www.hollywoodreporter.com",
  "d.newsweek.com",
  "media.cnn.com",
  "ychef.files.bbci.co.uk",
  "www.rollingstone.com",
  "abcnews.go.com",
  "npr.brightspotcdn.com",
  "nbcsports.brightspotcdn.com",
  "abcnews.go.com",
  "www.npr.org",
  "deadline.com",
  "www.businessinsider.com",
  "www.washingtonpost.com",
  "www.bbc.com",
  "images.wsj.net",
  "www.axios.com",
  "www.kqed.org",
  "images.axios.com",
  "dn.kqed.org",
  "cdn.kqed.org",
  "www.politico.com",
  "s.yimg.com",
  "variety.com"
];